env:
  browser: true
  es2021: true
parserOptions:
  ecmaVersion: 12
rules: {
  "semi": "error",
  "indent": ["error", "tab"],
  "no-mixed-spaces-and-tabs": ["error"],
  "brace-style": ["error", "allman"],
  "no-trailing-spaces": ["error", { "skipBlankLines": true }]
}
