name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: '78.155.199.43'
          username: 'root'
          key: ${{ secrets.SSH_KEY }}
          script: whoami
