name: CI

on:
  push:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Start linting'
        run: |
          npm install
          npx eslint . || { echo "::error file=app.js,line=10,col=15::Something went wrong"; exit 1; }

  deploy:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script_stop: true
          script: |
            cd ${{ secrets.SITE_DIR }}
            pwd
            ls -la