name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v1
      - uses: actions/checkout@v2
      - name: Install eslint
        run: npm install eslint
      - name: check eslint
        run: eslint .
